POST http://localhost:8080/api/users
Content-Type: application/json

{
    "username": "test",
    "name": "Test User",
    "password": "test",
    "domain": "test@smartraiser.ai",
    "orgName": "SmartRaiser"
}